### ISSUE TITLE
Which platforms break when not using principal name?

### ISSUE THREAD

**Issue by lachellel** [GSA/ficam-playbooks#84]
We need some feedback here to understand any repercussions with not using Principal Name mapping for network.  

Primarily for common implementations and office automation tools (cloud email providers, common federation services).

**Comment by idmken** [comment]
One microsoft article - https://docs.microsoft.com/en-us/azure/active-directory/hybrid/howto-troubleshoot-upn-changes#:~:text=By%20default%20the%20Azure%20AD%20Connect%20wizard%20uses,a%20single%20user%2C%20or%20for%20your%20entire%20organization.

**Comment by maxwellfunk** [comment]
potentially send an email out to ICAMSC listserv to see if this is even still a current issue

**Comment by grandamp** [comment]
I do not believe assertion of UPN (or not) is of any impact for Treasury.

It *would* be helpful for agencies to assert the user's verified email address in all Authentication certificates.

Otherwise, in order to interact with the user via email, we must have them self assert an email address.

If permitted, we then would need to *verify* the email address of a given user; which is not good from a CX perspective.
